// svelte-migration/src/lib/components/issues/issue-row.svelte
<script lang="ts">
	import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';

	import { resolve } from '$app/paths';

	import { Button } from '$lib/components/ui/button';
	import { cn } from '$lib/utils';

	import LabelBadge from './label-badge.svelte';
	import PriorityIndicator from './priority-indicator.svelte';
	import StatusIcon from './status-badge.svelte';

	import type { Doc, Id } from '$convex/_generated/dataModel';

	type Issue = Doc<'issues'>;
	type Label = Doc<'labels'>;

	let {
		slug,
		issue,
		labels
	}: {
		slug: string;
		issue: Issue;
		labels: Label[];
	} = $props();

	const issueLabels = $derived(labels.filter((l) => issue.labelIds.includes(l._id as Id<'labels'>)));

	const issueHref = $derived(resolve(`/org/${slug}/issues/${issue.number}` as '/'));
</script>

<Button
	href={issueHref}
	variant="ghost"
	class={cn(
		'hover:bg-accent group h-auto w-full cursor-pointer justify-start gap-3 rounded-none border-b border-border px-4 py-3',
		issue.status === 'closed' && 'opacity-60'
	)}
>
	<StatusIcon status={issue.status} />

	<span
		class="text-muted-foreground group-hover:text-foreground w-10 shrink-0 text-right font-mono text-xs transition-colors"
	>
		#{issue.number}
	</span>

	<div class="min-w-0 flex-1">
		<div class="flex items-center gap-2">
			<span
				class={cn(
					'truncate text-sm font-medium',
					issue.status === 'closed' && 'line-through'
				)}
			>
				{issue.title}
			</span>
			{#each issueLabels as label (label._id)}
				<LabelBadge name={label.name} color={label.color} />
			{/each}
		</div>
	</div>

	<PriorityIndicator priority={issue.priority} />

	<ChevronRightIcon
		class="text-muted-foreground h-3.5 w-3.5 opacity-0 transition-opacity group-hover:opacity-100"
		aria-hidden="true"
	/>
</Button>

// src/components/issues/issue-row.tsx
"use client";

import type { Doc } from "@/convex";

import { ChevronRight } from "lucide-react";
import { Link } from "@/components/ui/link";
import { useParams } from "next/navigation";

import { cn } from "@/lib/utils";

import { StatusIcon } from "./status-badge";
import { PriorityIndicator } from "./priority-indicator";
import { LabelBadge } from "./label-badge";

type Issue = Doc<"issues">;
type Label = Doc<"labels">;

export function IssueRow({ issue, labels }: { issue: Issue; labels: Label[] }) {
  const params = useParams<{ slug: string }>();
  const issueLabels = labels.filter((l) => issue.labelIds.includes(l._id));

  return (
    <Link
      href={`/org/${params.slug}/issues/${issue.number}`}
      className={cn(
        "flex items-center gap-3 border-b px-4 py-3 transition-colors hover:bg-accent cursor-pointer group",
        issue.status === "closed" && "opacity-60",
      )}
    >
      <StatusIcon status={issue.status} />

      <span className="text-xs text-muted-foreground font-mono shrink-0 w-10 text-right transition-colors group-hover:text-foreground">
        #{issue.number}
      </span>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "text-sm font-medium truncate",
              issue.status === "closed" && "line-through",
            )}
          >
            {issue.title}
          </span>
          {issueLabels.map((label) => (
            <LabelBadge key={label._id} name={label.name} color={label.color} />
          ))}
        </div>
      </div>

      <PriorityIndicator priority={issue.priority} />

      <ChevronRight className="h-3.5 w-3.5 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" />
    </Link>
  );
}
