// src/lib/components/issues/priority-indicator.svelte
<script lang="ts">
	import AlertTriangleIcon from '@lucide/svelte/icons/alert-triangle';
	import SignalHighIcon from '@lucide/svelte/icons/signal-high';
	import SignalLowIcon from '@lucide/svelte/icons/signal-low';
	import SignalMediumIcon from '@lucide/svelte/icons/signal-medium';

	import { cn } from '$lib/utils';

	type IssuePriority = 'urgent' | 'high' | 'medium' | 'low';

	const PRIORITY_CONFIG: Record<
		IssuePriority,
		{ label: string; className: string }
	> = {
		urgent: { label: 'Urgent', className: 'text-destructive' },
		high: { label: 'High', className: 'text-foreground' },
		medium: { label: 'Medium', className: 'text-muted-foreground' },
		low: { label: 'Low', className: 'text-muted-foreground/60' }
	};

	let {
		priority,
		showLabel = false,
		class: className = ''
	}: {
		priority: IssuePriority;
		showLabel?: boolean;
		class?: string;
	} = $props();

	const config = $derived(PRIORITY_CONFIG[priority]);
</script>

<span class={cn('inline-flex items-center gap-1.5 text-xs font-medium', config.className, className)}>
	{#if priority === 'urgent'}
		<AlertTriangleIcon class="h-3.5 w-3.5" aria-hidden="true" />
	{:else if priority === 'high'}
		<SignalHighIcon class="h-3.5 w-3.5" aria-hidden="true" />
	{:else if priority === 'medium'}
		<SignalMediumIcon class="h-3.5 w-3.5" aria-hidden="true" />
	{:else}
		<SignalLowIcon class="h-3.5 w-3.5" aria-hidden="true" />
	{/if}
	{#if showLabel}{config.label}{/if}
</span>

// src/components/issues/priority-indicator.tsx
import { SignalHigh, SignalMedium, SignalLow, AlertTriangle } from "lucide-react";

import { cn } from "@/lib/utils";

const PRIORITY_CONFIG = {
  urgent: {
    label: "Urgent",
    icon: AlertTriangle,
    className: "text-destructive",
  },
  high: {
    label: "High",
    icon: SignalHigh,
    className: "text-foreground",
  },
  medium: {
    label: "Medium",
    icon: SignalMedium,
    className: "text-muted-foreground",
  },
  low: {
    label: "Low",
    icon: SignalLow,
    className: "text-muted-foreground/60",
  },
} as const;

type IssuePriority = keyof typeof PRIORITY_CONFIG;

export function PriorityIndicator({
  priority,
  showLabel = false,
  className,
}: {
  priority: IssuePriority;
  showLabel?: boolean;
  className?: string;
}) {
  const config = PRIORITY_CONFIG[priority];
  const Icon = config.icon;

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 text-xs font-medium",
        config.className,
        className,
      )}
    >
      <Icon className="h-3.5 w-3.5" />
      {showLabel && config.label}
    </span>
  );
}
