// apps/web/src/app/invite/[id]/page.tsx
"use client";

import { Authenticated, AuthLoading, Unauthenticated } from "convex/react";
import { CheckCircle, Loader2, Mail, XCircle } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { ModeToggle } from "@/components/mode-toggle";
import { useAcceptInvitation, useInvitation, useRejectInvitation } from "@/hooks/use-organization";

function UnauthRedirect({ inviteId }: { inviteId: string }) {
  const router = useRouter();
  const redirected = useRef(false);

  useEffect(() => {
    if (redirected.current) return;
    redirected.current = true;
    // Preserve the invite URL so the user can return after sign-in
    const returnTo = encodeURIComponent(`/invite/${inviteId}`);
    router.replace(`/sign-in?returnTo=${returnTo}`);
  }, [router, inviteId]);

  return null;
}

function InviteContent({ inviteId }: { inviteId: string }) {
  const router = useRouter();
  const { data: invitation, isPending, isError } = useInvitation(inviteId);
  const acceptInvitation = useAcceptInvitation();
  const rejectInvitation = useRejectInvitation();
  const [outcome, setOutcome] = useState<"accepted" | "rejected" | null>(null);

  const handleAccept = async () => {
    try {
      await acceptInvitation.mutateAsync({ invitationId: inviteId });
      setOutcome("accepted");
      // Navigate to the org after a brief moment
      setTimeout(() => {
        router.push("/org");
      }, 1_500);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to accept invitation";
      setOutcome(null);
      alert(message);
    }
  };

  const handleReject = async () => {
    try {
      await rejectInvitation.mutateAsync({ invitationId: inviteId });
      setOutcome("rejected");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to reject invitation";
      setOutcome(null);
      alert(message);
    }
  };

  if (isPending) {
    return (
      <Card className="w-full max-w-sm">
        <CardHeader className="items-center text-center">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          <CardTitle className="text-sm">Loading invitation...</CardTitle>
        </CardHeader>
      </Card>
    );
  }

  if (isError || !invitation) {
    return (
      <Card className="w-full max-w-sm">
        <CardHeader className="items-center text-center">
          <XCircle className="h-8 w-8 text-destructive" />
          <CardTitle className="text-sm">Invitation not found</CardTitle>
          <CardDescription>
            This invitation may have expired, been cancelled, or doesn&apos;t exist.
          </CardDescription>
        </CardHeader>
        <CardFooter className="justify-center pb-4">
          <Button variant="outline" size="sm" onClick={() => router.push("/org")}>
            Go to dashboard
          </Button>
        </CardFooter>
      </Card>
    );
  }

  if (invitation.status !== "pending") {
    return (
      <Card className="w-full max-w-sm">
        <CardHeader className="items-center text-center">
          {invitation.status === "accepted" ? (
            <CheckCircle className="h-8 w-8 text-green-600" />
          ) : (
            <XCircle className="h-8 w-8 text-muted-foreground" />
          )}
          <CardTitle className="text-sm">Invitation {invitation.status}</CardTitle>
          <CardDescription>This invitation has already been {invitation.status}.</CardDescription>
        </CardHeader>
        <CardFooter className="justify-center pb-4">
          <Button variant="outline" size="sm" onClick={() => router.push("/org")}>
            Go to dashboard
          </Button>
        </CardFooter>
      </Card>
    );
  }

  if (outcome === "accepted") {
    return (
      <Card className="w-full max-w-sm">
        <CardHeader className="items-center text-center">
          <CheckCircle className="h-8 w-8 text-green-600" />
          <CardTitle className="text-sm">Invitation accepted</CardTitle>
          <CardDescription>Redirecting to your dashboard...</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  if (outcome === "rejected") {
    return (
      <Card className="w-full max-w-sm">
        <CardHeader className="items-center text-center">
          <XCircle className="h-8 w-8 text-muted-foreground" />
          <CardTitle className="text-sm">Invitation declined</CardTitle>
          <CardDescription>You have declined this invitation.</CardDescription>
        </CardHeader>
        <CardFooter className="justify-center pb-4">
          <Button variant="outline" size="sm" onClick={() => router.push("/sign-in")}>
            Go home
          </Button>
        </CardFooter>
      </Card>
    );
  }

  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="items-center text-center">
        <Mail className="h-8 w-8 text-muted-foreground" />
        <CardTitle className="text-sm">You&apos;ve been invited</CardTitle>
        <CardDescription>
          You&apos;ve been invited to join as <strong>{invitation.role}</strong>.
          {invitation.expiresAt && (
            <> This invitation expires on {new Date(invitation.expiresAt).toLocaleDateString()}.</>
          )}
        </CardDescription>
      </CardHeader>
      <CardFooter className="justify-center gap-3 pb-4">
        <Button
          variant="outline"
          size="sm"
          onClick={handleReject}
          disabled={rejectInvitation.isPending || acceptInvitation.isPending}
        >
          {rejectInvitation.isPending ? "Declining..." : "Decline"}
        </Button>
        <Button
          size="sm"
          onClick={handleAccept}
          disabled={acceptInvitation.isPending || rejectInvitation.isPending}
        >
          {acceptInvitation.isPending ? "Accepting..." : "Accept Invitation"}
        </Button>
      </CardFooter>
    </Card>
  );
}

export default function InvitePage() {
  const params = useParams<{ id: string }>();

  return (
    <div className="flex h-svh flex-col items-center justify-center bg-background px-4">
      <div className="absolute right-4 top-4">
        <ModeToggle />
      </div>
      <div className="mb-6 text-center">
        <h1 className="text-base font-bold tracking-tight">better-issues</h1>
        <p className="text-xs text-muted-foreground">Issue tracking for small teams</p>
      </div>

      <AuthLoading>
        <Card className="w-full max-w-sm">
          <CardHeader className="items-center text-center">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            <CardTitle className="text-sm">Loading...</CardTitle>
          </CardHeader>
        </Card>
      </AuthLoading>

      <Unauthenticated>
        <UnauthRedirect inviteId={params.id} />
      </Unauthenticated>

      <Authenticated>
        <InviteContent inviteId={params.id} />
      </Authenticated>
    </div>
  );
}

// src/routes/invite/[id]/+page.svelte
<script lang="ts">
	import CheckCircleIcon from '@lucide/svelte/icons/check-circle';
	import Loader2Icon from '@lucide/svelte/icons/loader-2';
	import MailIcon from '@lucide/svelte/icons/mail';
	import XCircleIcon from '@lucide/svelte/icons/x-circle';

	import type { PageProps } from './$types';
	import {
		acceptInvitation,
		getInvitation,
		rejectInvitation,
		type OrganizationInvitation
	} from '$lib/organization';
	import { gotoResolvedPath } from '$lib/goto-resolved';
	import ModeToggle from '$lib/components/mode-toggle.svelte';
	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card';

	let { params, data: _data }: PageProps = $props();

	let invitation = $state<OrganizationInvitation | null | undefined>(undefined);
	let loading = $state(true);

	let outcome = $state<'accepted' | 'rejected' | null>(null);
	let actionError = $state<string | null>(null);

	let accepting = $state(false);
	let rejecting = $state(false);

	let redirectTimer: ReturnType<typeof setTimeout> | undefined;
	let initialized = false;

	$effect(() => {
		if (initialized) return;
		initialized = true;

		void (async () => {
			try {
				const data = await getInvitation(params.id);
				invitation = data;
			} catch {
				invitation = null;
			} finally {
				loading = false;
			}
		})();

		return () => {
			if (redirectTimer !== undefined) {
				clearTimeout(redirectTimer);
			}
		};
	});

	async function handleAccept() {
		actionError = null;
		accepting = true;
		try {
			await acceptInvitation(params.id);
			outcome = 'accepted';
			redirectTimer = setTimeout(() => {
				void gotoResolvedPath('/org');
			}, 1_500);
		} catch (e) {
			outcome = null;
			actionError = e instanceof Error ? e.message : 'Failed to accept invitation';
		} finally {
			accepting = false;
		}
	}

	async function handleReject() {
		actionError = null;
		rejecting = true;
		try {
			await rejectInvitation(params.id);
			outcome = 'rejected';
		} catch (e) {
			outcome = null;
			actionError = e instanceof Error ? e.message : 'Failed to reject invitation';
		} finally {
			rejecting = false;
		}
	}

	function goOrg() {
		void gotoResolvedPath('/org');
	}

	function goSignIn() {
		void gotoResolvedPath('/sign-in');
	}
</script>

<div class="flex h-svh flex-col items-center justify-center bg-background px-4">
	<div class="absolute top-4 right-4">
		<ModeToggle />
	</div>
	<div class="mb-6 text-center">
		<h1 class="text-base font-bold tracking-tight">better-issues</h1>
		<p class="text-xs text-muted-foreground">Issue tracking for small teams</p>
	</div>

	{#if loading}
		<Card.Root class="w-full max-w-sm">
			<Card.Header class="items-center text-center">
				<Loader2Icon class="h-6 w-6 animate-spin text-muted-foreground" />
				<Card.Title class="text-sm">Loading invitation...</Card.Title>
			</Card.Header>
		</Card.Root>
	{:else if !invitation}
		<Card.Root class="w-full max-w-sm">
			<Card.Header class="items-center text-center">
				<XCircleIcon class="h-8 w-8 text-destructive" />
				<Card.Title class="text-sm">Invitation not found</Card.Title>
				<Card.Description>
					This invitation may have expired, been cancelled, or doesn’t exist.
				</Card.Description>
			</Card.Header>
			<Card.Footer class="justify-center pb-4">
				<Button variant="outline" size="sm" onclick={goOrg}>Go to dashboard</Button>
			</Card.Footer>
		</Card.Root>
	{:else if invitation.status !== 'pending'}
		<Card.Root class="w-full max-w-sm">
			<Card.Header class="items-center text-center">
				{#if invitation.status === 'accepted'}
					<CheckCircleIcon class="h-8 w-8 text-chart-1" />
				{:else}
					<XCircleIcon class="h-8 w-8 text-muted-foreground" />
				{/if}
				<Card.Title class="text-sm">Invitation {invitation.status}</Card.Title>
				<Card.Description>
					This invitation has already been {invitation.status}.
				</Card.Description>
			</Card.Header>
			<Card.Footer class="justify-center pb-4">
				<Button variant="outline" size="sm" onclick={goOrg}>Go to dashboard</Button>
			</Card.Footer>
		</Card.Root>
	{:else if outcome === 'accepted'}
		<Card.Root class="w-full max-w-sm">
			<Card.Header class="items-center text-center">
				<CheckCircleIcon class="h-8 w-8 text-green-600" />
				<Card.Title class="text-sm">Invitation accepted</Card.Title>
				<Card.Description>Redirecting to your dashboard...</Card.Description>
			</Card.Header>
		</Card.Root>
	{:else if outcome === 'rejected'}
		<Card.Root class="w-full max-w-sm">
			<Card.Header class="items-center text-center">
				<XCircleIcon class="h-8 w-8 text-muted-foreground" />
				<Card.Title class="text-sm">Invitation declined</Card.Title>
				<Card.Description>You have declined this invitation.</Card.Description>
			</Card.Header>
			<Card.Footer class="justify-center pb-4">
				<Button variant="outline" size="sm" onclick={goSignIn}>Go home</Button>
			</Card.Footer>
		</Card.Root>
	{:else}
		<Card.Root class="w-full max-w-sm">
			<Card.Header class="items-center text-center">
				<MailIcon class="h-8 w-8 text-muted-foreground" />
				<Card.Title class="text-sm">You’ve been invited</Card.Title>
				<Card.Description>
					{#if invitation.expiresAt}
						You’ve been invited to join as <strong>{invitation.role}</strong>. This invitation
						expires on {new Date(invitation.expiresAt).toLocaleDateString()}.
					{:else}
						You’ve been invited to join as <strong>{invitation.role}</strong>.
					{/if}
				</Card.Description>
			</Card.Header>
			{#if actionError}
				<Card.Content class="pt-0">
					<p class="text-center text-xs text-destructive" role="alert">{actionError}</p>
				</Card.Content>
			{/if}
			<Card.Footer class="justify-center gap-3 pb-4">
				<Button
					variant="outline"
					size="sm"
					onclick={() => void handleReject()}
					disabled={rejecting || accepting}
				>
					{rejecting ? 'Declining...' : 'Decline'}
				</Button>
				<Button size="sm" onclick={() => void handleAccept()} disabled={accepting || rejecting}>
					{accepting ? 'Accepting...' : 'Accept Invitation'}
				</Button>
			</Card.Footer>
		</Card.Root>
	{/if}
</div>
