// apps/web/src/app/org/[slug]/issues/new/page.tsx
"use client";

import type { Doc, Id } from "@better-issues/backend/convex/_generated/dataModel";
import type { TemplateSchema } from "@better-issues/backend/convex/lib/templateSchema";

import { api } from "@better-issues/backend/convex/_generated/api";
import { useMutation, useQuery } from "convex/react";
import { ArrowLeft, FileText, Search } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { TemplateFieldRenderer } from "@/components/issues/template-fields";
import { authClient } from "@/lib/auth-client";

type IssuePriority = "low" | "medium" | "high" | "urgent";

export default function NewIssuePage() {
  const params = useParams<{ slug: string }>();
  const router = useRouter();
  const { data: activeOrg } = authClient.useActiveOrganization();

  const templates = useQuery(
    api.templates.list,
    activeOrg ? { organizationId: activeOrg.id } : "skip",
  );
  const labels = useQuery(api.labels.list, activeOrg ? { organizationId: activeOrg.id } : "skip");

  const createIssue = useMutation(api.issues.create);

  const [step, setStep] = useState<"choose-template" | "form">("choose-template");
  const [selectedTemplate, setSelectedTemplate] = useState<Doc<"issueTemplates"> | null>(null);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<IssuePriority>("medium");
  const [selectedLabels, setSelectedLabels] = useState<Id<"labels">[]>([]);
  const [templateData, setTemplateData] = useState<Record<string, unknown>>({});
  const [submitting, setSubmitting] = useState(false);

  const parsedSchema: TemplateSchema | null = selectedTemplate
    ? (() => {
        try {
          return JSON.parse(selectedTemplate.schema) as TemplateSchema;
        } catch {
          return null;
        }
      })()
    : null;

  const handleTemplateSelect = (template: Doc<"issueTemplates"> | null) => {
    setSelectedTemplate(template);
    setTemplateData({});
    setStep("form");
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeOrg || !title.trim()) return;

    setSubmitting(true);
    try {
      const result = await createIssue({
        organizationId: activeOrg.id,
        title: title.trim(),
        description: description.trim() || undefined,
        priority,
        labelIds: selectedLabels,
        templateId: selectedTemplate?._id,
        templateData:
          Object.keys(templateData).length > 0 ? JSON.stringify(templateData) : undefined,
      });

      toast.success(`Issue #${result.number} created`);
      router.push(`/org/${params.slug}/issues/${result.number}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to create issue");
    } finally {
      setSubmitting(false);
    }
  };

  const toggleLabel = (labelId: Id<"labels">) => {
    setSelectedLabels((prev) =>
      prev.includes(labelId) ? prev.filter((id) => id !== labelId) : [...prev, labelId],
    );
  };

  if (!activeOrg) {
    return (
      <div className="p-6 space-y-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-32 w-full" />
      </div>
    );
  }

  // Step 1: Choose template (per article best practice 3)
  if (step === "choose-template") {
    return (
      <div className="flex h-full flex-col">
        <div className="flex items-center gap-3 border-b px-4 py-3">
          <Link href={`/org/${params.slug}`}>
            <Button variant="ghost" size="sm">
              <ArrowLeft className="h-3.5 w-3.5" />
            </Button>
          </Link>
          <h1 className="text-sm font-bold">New Issue</h1>
        </div>

        <div className="flex-1 p-6">
          <div className="mx-auto max-w-lg space-y-4">
            <div>
              <h2 className="text-base font-medium">Choose a template</h2>
              <p className="text-sm text-muted-foreground">
                Select a template for structured reporting, or start blank.
              </p>
            </div>

            <div className="flex items-center gap-2 border px-3 py-2 text-sm text-muted-foreground">
              <Search className="h-3.5 w-3.5" />
              <span>Tip: Search existing issues before creating a new one (Cmd+K)</span>
            </div>

            <button
              onClick={() => handleTemplateSelect(null)}
              className="flex w-full items-center gap-3 border p-4 text-left transition-colors hover:bg-accent cursor-pointer"
            >
              <FileText className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-sm font-medium">Blank issue</p>
                <p className="text-xs text-muted-foreground">
                  Start from scratch with title and description
                </p>
              </div>
            </button>

            {templates === undefined ? (
              <div className="space-y-2">
                <Skeleton className="h-16 w-full" />
                <Skeleton className="h-16 w-full" />
              </div>
            ) : (
              templates.map((template: Doc<"issueTemplates">) => (
                <button
                  key={template._id}
                  onClick={() => handleTemplateSelect(template)}
                  className="flex w-full items-center gap-3 border p-4 text-left transition-colors hover:bg-accent cursor-pointer"
                >
                  <FileText className="h-5 w-5 text-muted-foreground" />
                  <div>
                    <p className="text-sm font-medium">{template.name}</p>
                    <p className="text-xs text-muted-foreground">{template.description}</p>
                  </div>
                </button>
              ))
            )}
          </div>
        </div>
      </div>
    );
  }

  // Step 2: Issue form
  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center gap-3 border-b px-4 py-3">
        <Button variant="ghost" size="sm" onClick={() => setStep("choose-template")}>
          <ArrowLeft className="h-3.5 w-3.5" />
        </Button>
        <h1 className="text-sm font-bold">
          New Issue
          {selectedTemplate && (
            <span className="ml-2 font-normal text-muted-foreground">
              / {selectedTemplate.name}
            </span>
          )}
        </h1>
      </div>

      <div className="flex-1 overflow-auto p-6">
        <form onSubmit={handleSubmit} className="mx-auto max-w-lg space-y-6">
          {/* Core fields */}
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="title">
                Title <span className="text-destructive">*</span>
              </Label>
              <Input
                id="title"
                placeholder="Brief summary of the issue"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                autoFocus
              />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                placeholder="Provide more details..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={4}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label>Priority</Label>
                <Select value={priority} onValueChange={(v) => setPriority(v as IssuePriority)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="urgent">Urgent</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="grid gap-2">
                <Label>Labels</Label>
                <div className="flex flex-wrap gap-1.5 min-h-9 items-center border px-3 py-1.5">
                  {labels && labels.length > 0 ? (
                    labels.map((label: { _id: Id<"labels">; name: string; color: string }) => (
                      <button
                        key={label._id}
                        type="button"
                        onClick={() => toggleLabel(label._id)}
                        className="inline-flex items-center gap-1 border px-1.5 py-0.5 text-xs cursor-pointer transition-colors"
                        style={{
                          borderColor: selectedLabels.includes(label._id) ? label.color : undefined,
                          backgroundColor: selectedLabels.includes(label._id)
                            ? `${label.color}20`
                            : undefined,
                          color: selectedLabels.includes(label._id) ? label.color : undefined,
                        }}
                      >
                        <span className="h-2 w-2" style={{ backgroundColor: label.color }} />
                        {label.name}
                      </button>
                    ))
                  ) : (
                    <span className="text-xs text-muted-foreground">No labels</span>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Template fields */}
          {parsedSchema && parsedSchema.fields.length > 0 && (
            <>
              <Separator />
              <div className="space-y-4">
                <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                  Template Fields
                </p>
                {parsedSchema.fields.map((field) => (
                  <TemplateFieldRenderer
                    key={field.key}
                    field={field}
                    value={templateData[field.key]}
                    onChange={(value) =>
                      setTemplateData((prev) => ({
                        ...prev,
                        [field.key]: value,
                      }))
                    }
                  />
                ))}
              </div>
            </>
          )}

          <div className="flex gap-3">
            <Button type="submit" disabled={submitting || !title.trim()} className="flex-1">
              {submitting ? "Creating..." : "Create Issue"}
            </Button>
            <Link href={`/org/${params.slug}`}>
              <Button type="button" variant="outline">
                Cancel
              </Button>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
}

// src/routes/org/[slug]/issues/new/+page.svelte
<script lang="ts">
	import ArrowLeftIcon from '@lucide/svelte/icons/arrow-left';
	import FileTextIcon from '@lucide/svelte/icons/file-text';
	import SearchIcon from '@lucide/svelte/icons/search';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { useMutation, useQuery } from '@mmailaender/convex-svelte';
	import { toast } from 'svelte-sonner';

	import { api } from '$convex/_generated/api';
	import type { Id } from '$convex/_generated/dataModel';
	import type { TemplateSchema } from '$convex/lib/templateSchema';
	import LabelBadge from '$lib/components/issues/label-badge.svelte';
	import TemplateFieldRenderer from '$lib/components/issues/template-field-renderer.svelte';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { Textarea } from '$lib/components/ui/textarea';
	import { getWorkspace } from '$lib/workspace-context';

	type IssuePriority = 'low' | 'medium' | 'high' | 'urgent';

	const workspace = getWorkspace();
	const createIssue = useMutation(api.issues.create);

	const slug = $derived(page.params.slug ?? '');
	const organizationId = $derived(workspace.organizationId);
	const templatesQuery = useQuery(api.templates.list, () =>
		organizationId ? { organizationId } : 'skip'
	);
	const labelsQuery = useQuery(api.labels.list, () =>
		organizationId ? { organizationId } : 'skip'
	);

	let selectedTemplateId = $state<Id<'issueTemplates'> | null>(null);
	let templateChosen = $state(false);
	let form = $state({
		title: '',
		description: '',
		priority: 'medium' as IssuePriority
	});
	let selectedLabels = $state<Id<'labels'>[]>([]);
	let templateData = $state<Record<string, unknown>>({});
	let submitting = $state(false);

	const templateParam = $derived(
		page.url.searchParams.get('template') ?? page.url.searchParams.get('templates')
	);
	const templates = $derived(templatesQuery.data ?? []);
	const labels = $derived(labelsQuery.data ?? []);

	const selectedTemplateFromSearch = $derived.by(() => {
		if (!templateParam) {
			return undefined;
		}
		if (templateParam === 'blank') {
			return null;
		}

		return templates.find((template) => template._id === templateParam) ?? undefined;
	});

	const selectedTemplate = $derived.by(() => {
		if (selectedTemplateFromSearch !== undefined) {
			return selectedTemplateFromSearch;
		}

		if (!templateChosen) {
			return undefined;
		}

		return templates.find((template) => template._id === selectedTemplateId) ?? null;
	});

	const parsedSchema = $derived.by(() => {
		if (!selectedTemplate) {
			return null;
		}

		try {
			return JSON.parse(selectedTemplate.schema) as TemplateSchema;
		} catch {
			return null;
		}
	});

	const showingForm = $derived(selectedTemplateFromSearch !== undefined || templateChosen);

	function toggleLabel(labelId: Id<'labels'>) {
		selectedLabels = selectedLabels.includes(labelId)
			? selectedLabels.filter((id) => id !== labelId)
			: [...selectedLabels, labelId];
	}

	function chooseTemplate(templateId: Id<'issueTemplates'> | null) {
		selectedTemplateId = templateId;
		templateChosen = true;
		templateData = {};
	}

	async function goBackToSelection() {
		templateChosen = false;
		selectedTemplateId = null;
		templateData = {};
		await goto(`/org/${slug}/issues/new`);
	}

	async function handleSubmit(event: SubmitEvent) {
		event.preventDefault();
		if (!organizationId || !form.title.trim()) {
			return;
		}

		submitting = true;
		try {
			const result = await createIssue({
				organizationId,
				title: form.title.trim(),
				description: form.description.trim() || undefined,
				priority: form.priority,
				labelIds: selectedLabels,
				templateId: selectedTemplate?._id,
				templateData:
					Object.keys(templateData).length > 0 ? JSON.stringify(templateData) : undefined
			});

			toast.success(`Issue #${result.number} created`);
			await goto(`/org/${slug}/issues/${result.number}`);
		} catch (error) {
			toast.error(error instanceof Error ? error.message : 'Failed to create issue');
			submitting = false;
		}
	}
</script>

<div class="flex h-full flex-col">
	<div class="flex items-center gap-3 border-b border-border px-4 py-3">
		{#if showingForm}
			<Button variant="ghost" size="sm" onclick={() => void goBackToSelection()}>
				<ArrowLeftIcon class="h-3.5 w-3.5" />
			</Button>
		{/if}
		<h1 class="text-sm font-bold">
			New Issue
			{#if selectedTemplate}
				<span class="ml-2 font-normal text-muted-foreground">/ {selectedTemplate.name}</span>
			{/if}
		</h1>
	</div>

	<div class="flex-1 overflow-auto p-6">
		{#if !organizationId}
			<div class="space-y-4">
				<Skeleton class="h-8 w-48" />
				<Skeleton class="h-10 w-full" />
				<Skeleton class="h-32 w-full" />
			</div>
		{:else if !showingForm}
			<div class="mx-auto max-w-lg space-y-4">
				<div>
					<h2 class="text-base font-medium">Choose a template</h2>
					<p class="text-sm text-muted-foreground">
						Select a template for structured reporting, or start blank.
					</p>
				</div>

				<div
					class="flex items-center gap-2 border border-border px-3 py-2 text-sm text-muted-foreground"
				>
					<SearchIcon class="h-3.5 w-3.5" />
					<span>Tip: search existing issues before creating a new one.</span>
				</div>

				<button
					type="button"
					onclick={() => chooseTemplate(null)}
					class="flex w-full cursor-pointer items-center gap-3 border border-border p-4 text-left transition-colors hover:bg-accent"
				>
					<FileTextIcon class="h-5 w-5 text-muted-foreground" />
					<div>
						<p class="text-sm font-medium">Blank issue</p>
						<p class="text-xs text-muted-foreground">
							Start from scratch with title and description
						</p>
					</div>
				</button>

				{#if templatesQuery.data === undefined}
					<div class="space-y-2">
						<Skeleton class="h-16 w-full" />
						<Skeleton class="h-16 w-full" />
					</div>
				{:else}
					{#each templates as template (template._id)}
						<button
							type="button"
							onclick={() => chooseTemplate(template._id)}
							class="flex w-full cursor-pointer items-center gap-3 border border-border p-4 text-left transition-colors hover:bg-accent"
						>
							<FileTextIcon class="h-5 w-5 text-muted-foreground" />
							<div>
								<p class="text-sm font-medium">{template.name}</p>
								<p class="text-xs text-muted-foreground">{template.description}</p>
							</div>
						</button>
					{/each}
				{/if}
			</div>
		{:else}
			<form class="mx-auto max-w-lg space-y-6" onsubmit={handleSubmit}>
				<div class="grid gap-4">
					<div class="grid gap-2">
						<Label for="new-issue-title">
							Title <span class="text-destructive">*</span>
						</Label>
						<Input
							id="new-issue-title"
							placeholder="Brief summary of the issue"
							bind:value={form.title}
						/>
					</div>

					<div class="grid gap-2">
						<Label for="new-issue-description">Description</Label>
						<Textarea
							id="new-issue-description"
							rows={4}
							placeholder="Provide more details..."
							bind:value={form.description}
						/>
					</div>

					<div class="grid gap-2">
						<Label for="new-issue-priority">Priority</Label>
						<select
							id="new-issue-priority"
							class="h-8 w-full rounded-none border border-input bg-background px-2 text-sm text-foreground outline-none"
							bind:value={form.priority}
						>
							<option value="low">Low</option>
							<option value="medium">Medium</option>
							<option value="high">High</option>
							<option value="urgent">Urgent</option>
						</select>
					</div>

					<div class="grid gap-2">
						<Label>Labels</Label>
						<div class="flex flex-wrap gap-2">
							{#if labels.length === 0}
								<p class="text-xs text-muted-foreground">No labels configured yet.</p>
							{:else}
								{#each labels as label (label._id)}
									<button
										type="button"
										class:selected={selectedLabels.includes(label._id)}
										class="cursor-pointer transition-opacity"
										onclick={() => toggleLabel(label._id)}
									>
										<LabelBadge
											name={label.name}
											color={label.color}
											class={!selectedLabels.includes(label._id) ? 'opacity-40' : ''}
										/>
									</button>
								{/each}
							{/if}
						</div>
					</div>
				</div>

				{#if parsedSchema}
					<div class="space-y-4">
						<div>
							<h2 class="text-sm font-medium">{selectedTemplate?.name}</h2>
							<p class="text-xs text-muted-foreground">{selectedTemplate?.description}</p>
						</div>

						{#each parsedSchema.fields as field (field.key)}
							<TemplateFieldRenderer
								{field}
								bind:value={templateData[field.key]}
								{organizationId}
							/>
						{/each}
					</div>
				{/if}

				<div class="flex gap-3">
					<Button type="submit" class="flex-1" disabled={submitting || !form.title.trim()}>
						{submitting ? 'Creating...' : 'Create Issue'}
					</Button>
					<Button type="button" variant="outline" onclick={() => void goto(`/org/${slug}`)}>
						Cancel
					</Button>
				</div>
			</form>
		{/if}
	</div>
</div>
