// apps/web/src/app/org/[slug]/issues/[number]/page.tsx
"use client";

import type { Route } from "next";
import type { TemplateSchema, Id } from "@/convex";

import { api } from "@/convex";
import { useMutation, useQuery } from "convex/react";
import { ArrowLeft, Pencil, Trash2, Clock } from "lucide-react";
import { Link } from "@/components/ui/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Select, SelectContent, SelectItem, SelectTrigger } from "@/components/ui/select";
import { StatusBadge } from "@/components/issues/status-badge";
import { PriorityIndicator } from "@/components/issues/priority-indicator";
import { LabelBadge } from "@/components/issues/label-badge";
import { authClient } from "@/lib/auth-client";
import { formatDate } from "@/lib/utils";

type IssueStatus = "open" | "in_progress" | "closed";
type IssuePriority = "low" | "medium" | "high" | "urgent";

export default function IssueDetailPage() {
  const params = useParams<{ slug: string; number: string }>();
  const router = useRouter();
  const { data: activeOrg } = authClient.useActiveOrganization();

  const issueNumber = parseInt(params.number, 10);

  const issue = useQuery(
    api.issues.getByNumber,
    activeOrg ? { organizationId: activeOrg.id, number: issueNumber } : "skip",
  );

  const labels = useQuery(api.labels.list, activeOrg ? { organizationId: activeOrg.id } : "skip");

  const template = useQuery(
    api.templates.get,
    issue?.templateId ? { templateId: issue.templateId } : "skip",
  );

  const updateIssue = useMutation(api.issues.update).withOptimisticUpdate((localStore, args) => {
    if (!activeOrg) return;
    const current = localStore.getQuery(api.issues.getByNumber, {
      organizationId: activeOrg.id,
      number: issueNumber,
    });
    if (current !== undefined && current !== null) {
      const updates: Record<string, unknown> = { updatedAt: Date.now() };
      if (args.title !== undefined) updates.title = args.title;
      if (args.description !== undefined) updates.description = args.description;
      if (args.priority !== undefined) updates.priority = args.priority;
      if (args.labelIds !== undefined) updates.labelIds = args.labelIds;
      localStore.setQuery(
        api.issues.getByNumber,
        { organizationId: activeOrg.id, number: issueNumber },
        { ...current, ...updates },
      );
    }
  });
  const updateStatus = useMutation(api.issues.updateStatus).withOptimisticUpdate(
    (localStore, args) => {
      if (!activeOrg) return;
      const current = localStore.getQuery(api.issues.getByNumber, {
        organizationId: activeOrg.id,
        number: issueNumber,
      });
      if (current !== undefined && current !== null) {
        localStore.setQuery(
          api.issues.getByNumber,
          { organizationId: activeOrg.id, number: issueNumber },
          {
            ...current,
            status: args.status,
            updatedAt: Date.now(),
            closedAt:
              args.status === "closed"
                ? Date.now()
                : current.status === "closed"
                  ? undefined
                  : current.closedAt,
          },
        );
      }
    },
  );
  const removeIssue = useMutation(api.issues.remove);

  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState("");
  const [editDescription, setEditDescription] = useState("");

  if (!activeOrg || issue === undefined) {
    return (
      <div className="flex h-full flex-col">
        <div className="flex items-center gap-3 border-b px-4 py-3">
          <Skeleton className="h-8 w-8" />
          <Skeleton className="h-5 w-48" />
        </div>
        <div className="p-6 space-y-4">
          <Skeleton className="h-8 w-96" />
          <Skeleton className="h-32 w-full" />
        </div>
      </div>
    );
  }

  if (issue === null) {
    return (
      <div className="flex h-full flex-col items-center justify-center">
        <p className="text-sm font-medium">Issue not found</p>
        <Link href={`/org/${params.slug}` as Route}>
          <Button variant="ghost" size="sm" className="mt-2">
            Back to issues
          </Button>
        </Link>
      </div>
    );
  }

  const parsedTemplateData: Record<string, unknown> = issue.templateData
    ? (() => {
        try {
          return JSON.parse(issue.templateData) as Record<string, unknown>;
        } catch {
          return {};
        }
      })()
    : {};

  const parsedSchema: TemplateSchema | null = template
    ? (() => {
        try {
          return JSON.parse(template.schema) as TemplateSchema;
        } catch {
          return null;
        }
      })()
    : null;

  const handleStartEdit = () => {
    setEditTitle(issue.title);
    setEditDescription(issue.description ?? "");
    setEditing(true);
  };

  const handleSaveEdit = async () => {
    try {
      await updateIssue({
        issueId: issue._id,
        title: editTitle,
        description: editDescription || undefined,
      });
      setEditing(false);
      toast.success("Issue updated");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update");
    }
  };

  const handleStatusChange = async (status: IssueStatus) => {
    try {
      await updateStatus({ issueId: issue._id, status });
      toast.success(`Status changed to ${status.replace("_", " ")}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update status");
    }
  };

  const handlePriorityChange = async (priority: IssuePriority) => {
    try {
      await updateIssue({ issueId: issue._id, priority });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update priority");
    }
  };

  const handleLabelToggle = async (labelId: Id<"labels">) => {
    const newLabels = issue.labelIds.includes(labelId)
      ? issue.labelIds.filter((id: Id<"labels">) => id !== labelId)
      : [...issue.labelIds, labelId];

    try {
      await updateIssue({ issueId: issue._id, labelIds: newLabels });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update labels");
    }
  };

  const handleDelete = async () => {
    if (!confirm("Are you sure you want to delete this issue?")) return;
    try {
      await removeIssue({ issueId: issue._id });
      toast.success("Issue deleted");
      router.push(`/org/${params.slug}` as Route);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to delete");
    }
  };

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="flex items-center justify-between border-b px-4 py-3">
        <div className="flex items-center gap-3">
          <Link href={`/org/${params.slug}` as Route}>
            <Button variant="ghost" size="sm">
              <ArrowLeft className="h-3.5 w-3.5" />
            </Button>
          </Link>
          <span className="text-sm text-muted-foreground font-mono">#{issue.number}</span>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={handleStartEdit} className="gap-1.5">
            <Pencil className="h-3.5 w-3.5" />
            Edit
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleDelete}
            className="gap-1.5 text-destructive hover:text-destructive"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto">
        <div className="mx-auto max-w-3xl p-6">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-[1fr_220px]">
            {/* Main content */}
            <div className="space-y-6">
              {editing ? (
                <div className="space-y-4">
                  <Input
                    value={editTitle}
                    onChange={(e) => setEditTitle(e.target.value)}
                    className="text-lg font-bold"
                    autoFocus
                  />
                  <Textarea
                    value={editDescription}
                    onChange={(e) => setEditDescription(e.target.value)}
                    rows={6}
                    placeholder="Description..."
                  />
                  <div className="flex gap-2">
                    <Button size="sm" onClick={handleSaveEdit}>
                      Save
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => setEditing(false)}>
                      Cancel
                    </Button>
                  </div>
                </div>
              ) : (
                <div>
                  <h1 className="text-lg font-bold">{issue.title}</h1>
                  {issue.description && (
                    <p className="mt-3 text-sm text-muted-foreground whitespace-pre-wrap">
                      {issue.description}
                    </p>
                  )}
                </div>
              )}

              {/* Template data */}
              {parsedSchema && Object.keys(parsedTemplateData).length > 0 && (
                <>
                  <Separator />
                  <div className="space-y-4">
                    <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                      {template?.name ?? "Template Data"}
                    </p>
                    {parsedSchema.fields.map((field) => {
                      const value = parsedTemplateData[field.key];
                      if (value === undefined || value === null || value === "") return null;
                      return (
                        <div key={field.key} className="space-y-1">
                          <p className="text-xs font-medium text-muted-foreground">{field.label}</p>
                          <p className="text-sm whitespace-pre-wrap">
                            {field.type === "checkbox" ? (value ? "Yes" : "No") : String(value)}
                          </p>
                        </div>
                      );
                    })}
                  </div>
                </>
              )}
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              <div className="space-y-3">
                <Label className="text-xs text-muted-foreground uppercase tracking-wider">
                  Status
                </Label>
                <Select
                  value={issue.status}
                  onValueChange={(v) => handleStatusChange(v as IssueStatus)}
                >
                  <SelectTrigger className="h-8">
                    <StatusBadge status={issue.status} />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="open">Open</SelectItem>
                    <SelectItem value="in_progress">In Progress</SelectItem>
                    <SelectItem value="closed">Closed</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-3">
                <Label className="text-xs text-muted-foreground uppercase tracking-wider">
                  Priority
                </Label>
                <Select
                  value={issue.priority}
                  onValueChange={(v) => handlePriorityChange(v as IssuePriority)}
                >
                  <SelectTrigger className="h-8">
                    <PriorityIndicator priority={issue.priority} showLabel />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="urgent">Urgent</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-3">
                <Label className="text-xs text-muted-foreground uppercase tracking-wider">
                  Labels
                </Label>
                <div className="flex flex-wrap gap-1.5">
                  {labels && labels.length > 0 ? (
                    labels.map((label: { _id: Id<"labels">; name: string; color: string }) => (
                      <button
                        key={label._id}
                        onClick={() => handleLabelToggle(label._id)}
                        className="cursor-pointer transition-opacity"
                        style={{
                          opacity: issue.labelIds.includes(label._id) ? 1 : 0.4,
                        }}
                      >
                        <LabelBadge name={label.name} color={label.color} />
                      </button>
                    ))
                  ) : (
                    <span className="text-xs text-muted-foreground">No labels configured</span>
                  )}
                </div>
              </div>

              <Separator />

              <div className="space-y-2 text-xs text-muted-foreground">
                <div className="flex items-center gap-1.5">
                  <Clock className="h-3 w-3" />
                  Created {formatDate(issue.createdAt)}
                </div>
                {issue.updatedAt !== issue.createdAt && (
                  <div className="flex items-center gap-1.5">
                    <Clock className="h-3 w-3" />
                    Updated {formatDate(issue.updatedAt)}
                  </div>
                )}
                {issue.closedAt && (
                  <div className="flex items-center gap-1.5">
                    <Clock className="h-3 w-3" />
                    Closed {formatDate(issue.closedAt)}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/org/[slug]/issues/[number]/+page.svelte
<script lang="ts">
  import ArrowLeftIcon from "@lucide/svelte/icons/arrow-left";
  import ClockIcon from "@lucide/svelte/icons/clock";
  import PencilIcon from "@lucide/svelte/icons/pencil";
  import Trash2Icon from "@lucide/svelte/icons/trash-2";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { useMutation, useQuery } from "@mmailaender/convex-svelte";
  import { toast } from "svelte-sonner";

  import { api } from "$convex/_generated/api";
  import type { Id } from "$convex/_generated/dataModel";
  import type { TemplateSchema } from "$convex/lib/templateSchema";
  import { getIssueSnapshot } from "$lib/issue-snapshot-cache";
  import ConfirmDialog from "$lib/components/confirm-dialog.svelte";
  import LabelBadge from "$lib/components/issues/label-badge.svelte";
  import PriorityIndicator from "$lib/components/issues/priority-indicator.svelte";
  import StatusBadge from "$lib/components/issues/status-badge.svelte";
  import TemplateFieldRenderer from "$lib/components/issues/template-field-renderer.svelte";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { Separator } from "$lib/components/ui/separator";
  import { Skeleton } from "$lib/components/ui/skeleton";
  import { Textarea } from "$lib/components/ui/textarea";
  import { formatDate } from "$lib/utils";
  import { getWorkspace } from "$lib/workspace-context";

  type IssueStatus = "open" | "in_progress" | "closed";
  type IssuePriority = "low" | "medium" | "high" | "urgent";

  const workspace = getWorkspace();
  const slug = $derived(page.params.slug ?? "");
  const issueNumber = $derived(Number.parseInt(page.params.number ?? "", 10));
  const organizationId = $derived(workspace.organizationId);

  const issueQuery = useQuery(
    api.issues.getByNumber,
    () =>
      organizationId && Number.isFinite(issueNumber)
        ? { organizationId, number: issueNumber }
        : "skip",
  );
  const labelsQuery = useQuery(
    api.labels.list,
    () => (organizationId ? { organizationId } : "skip"),
  );
  const templateQuery = useQuery(
    api.templates.get,
    () => (issueQuery.data?.templateId ? { templateId: issueQuery.data.templateId } : "skip"),
  );

  const updateIssue = useMutation(api.issues.update);
  const updateStatus = useMutation(api.issues.updateStatus);
  const removeIssue = useMutation(api.issues.remove);

  let editing = $state(false);
  let editTitle = $state("");
  let editDescription = $state("");
  let deleteOpen = $state(false);

  const cachedIssue = $derived(
    organizationId && Number.isFinite(issueNumber)
      ? getIssueSnapshot(organizationId, issueNumber)
      : undefined
  );
  const issue = $derived(issueQuery.data ?? cachedIssue);
  const labels = $derived(labelsQuery.data ?? []);
  const parsedTemplateData = $derived.by(() => {
    if (!issue?.templateData) {
      return {} as Record<string, unknown>;
    }

    try {
      return JSON.parse(issue.templateData) as Record<string, unknown>;
    } catch {
      return {};
    }
  });
  const parsedSchema = $derived.by(() => {
    if (!templateQuery.data) {
      return null;
    }

    try {
      return JSON.parse(templateQuery.data.schema) as TemplateSchema;
    } catch {
      return null;
    }
  });

  function startEdit() {
    if (!issue) return;
    editTitle = issue.title;
    editDescription = issue.description ?? "";
    editing = true;
  }

  async function saveEdit() {
    if (!issue) return;

    try {
      await updateIssue({
        issueId: issue._id,
        title: editTitle.trim(),
        description: editDescription.trim() || undefined,
      });
      editing = false;
      toast.success("Issue updated");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update issue");
    }
  }

  async function changeStatus(status: IssueStatus) {
    if (!issue) return;
    try {
      await updateStatus({ issueId: issue._id, status });
      toast.success(`Status changed to ${status.replace("_", " ")}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update status");
    }
  }

  async function changePriority(priority: IssuePriority) {
    if (!issue) return;
    try {
      await updateIssue({ issueId: issue._id, priority });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update priority");
    }
  }

  async function toggleLabel(labelId: Id<"labels">) {
    if (!issue) return;

    const nextLabels = issue.labelIds.includes(labelId)
      ? issue.labelIds.filter((id) => id !== labelId)
      : [...issue.labelIds, labelId];

    try {
      await updateIssue({ issueId: issue._id, labelIds: nextLabels });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update labels");
    }
  }

  async function deleteIssue() {
    if (!issue) return;
    try {
      await removeIssue({ issueId: issue._id });
      toast.success("Issue deleted");
      await goto(`/org/${slug}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to delete issue");
    }
  }
</script>

<div class="flex h-full flex-col">
  <div class="border-border flex items-center justify-between border-b px-4 py-3">
    <div class="flex items-center gap-3">
      <Button variant="ghost" size="sm" href={`/org/${slug}`}>
        <ArrowLeftIcon class="h-3.5 w-3.5" />
      </Button>
      {#if issue}
        <span class="text-muted-foreground font-mono text-sm">#{issue.number}</span>
      {:else}
        <Skeleton class="h-4 w-10" />
      {/if}
    </div>
    {#if issue}
      <div class="flex items-center gap-2">
        <Button variant="ghost" size="sm" class="gap-1.5" onclick={startEdit}>
          <PencilIcon class="h-3.5 w-3.5" />
          Edit
        </Button>
        <Button
          variant="ghost"
          size="sm"
          class="text-destructive hover:text-destructive"
          onclick={() => (deleteOpen = true)}
        >
          <Trash2Icon class="h-3.5 w-3.5" />
        </Button>
      </div>
    {/if}
  </div>

  <div class="flex-1 overflow-auto">
    {#if organizationId === undefined || issue === undefined}
      <div class="space-y-4 p-6">
        <Skeleton class="h-8 w-40" />
        <Skeleton class="h-10 w-full" />
        <Skeleton class="h-32 w-full" />
      </div>
    {:else if issue === null}
      <div class="flex h-full flex-col items-center justify-center gap-3">
        <p class="text-sm font-medium">Issue not found</p>
        <Button variant="outline" size="sm" href={`/org/${slug}`}>Back to issues</Button>
      </div>
    {:else}
      <div class="mx-auto grid max-w-3xl gap-8 p-6 md:grid-cols-[1fr_220px]">
        <div class="space-y-6">
          {#if editing}
            <div class="space-y-4">
              <Input bind:value={editTitle} class="text-lg font-bold" />
              <Textarea bind:value={editDescription} rows={6} placeholder="Description..." />
              <div class="flex gap-2">
                <Button size="sm" onclick={() => void saveEdit()}>Save</Button>
                <Button size="sm" variant="outline" onclick={() => (editing = false)}>Cancel</Button>
              </div>
            </div>
          {:else}
            <div>
              <h1 class="text-lg font-bold">{issue.title}</h1>
              {#if issue.description}
                <p class="text-muted-foreground mt-3 whitespace-pre-wrap text-sm">{issue.description}</p>
              {/if}
            </div>
          {/if}

          {#if parsedSchema && Object.keys(parsedTemplateData).length > 0}
            <Separator />
            <div class="space-y-4">
              <p class="text-muted-foreground text-xs font-medium uppercase tracking-wider">
                {templateQuery.data?.name ?? "Template Data"}
              </p>
              {#each parsedSchema.fields as field (field.key)}
                {#if parsedTemplateData[field.key] !== undefined && parsedTemplateData[field.key] !== ""}
                  <TemplateFieldRenderer
                    {field}
                    value={parsedTemplateData[field.key]}
                    readOnly
                    organizationId={organizationId}
                    issueId={issue._id}
                  />
                {/if}
              {/each}
            </div>
          {/if}
        </div>

        <div class="space-y-6">
          <div class="space-y-3">
            <Label for="issue-status" class="text-muted-foreground text-xs uppercase tracking-wider">
              Status
            </Label>
            <div class="border-border flex items-center gap-2 border px-2 py-2">
              <StatusBadge status={issue.status} />
              <select
                id="issue-status"
                class="bg-background w-full text-sm outline-none"
                value={issue.status}
                onchange={(event) =>
                  void changeStatus((event.currentTarget as HTMLSelectElement).value as IssueStatus)}
              >
                <option value="open">Open</option>
                <option value="in_progress">In Progress</option>
                <option value="closed">Closed</option>
              </select>
            </div>
          </div>

          <div class="space-y-3">
            <Label for="issue-priority" class="text-muted-foreground text-xs uppercase tracking-wider">
              Priority
            </Label>
            <div class="border-border flex items-center gap-2 border px-2 py-2">
              <PriorityIndicator priority={issue.priority} />
              <select
                id="issue-priority"
                class="bg-background w-full text-sm outline-none"
                value={issue.priority}
                onchange={(event) =>
                  void changePriority(
                    (event.currentTarget as HTMLSelectElement).value as IssuePriority,
                  )}
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
            </div>
          </div>

          <div class="space-y-3">
            <Label class="text-muted-foreground text-xs uppercase tracking-wider">Labels</Label>
            <div class="flex flex-wrap gap-2">
              {#if labels.length === 0}
                <span class="text-muted-foreground text-xs">No labels configured</span>
              {:else}
                {#each labels as label (label._id)}
                  <button
                    type="button"
                    class={!issue.labelIds.includes(label._id) ? "opacity-40" : ""}
                    onclick={() => void toggleLabel(label._id)}
                  >
                    <LabelBadge name={label.name} color={label.color} />
                  </button>
                {/each}
              {/if}
            </div>
          </div>

          <Separator />

          <div class="text-muted-foreground space-y-2 text-xs">
            <div class="flex items-center gap-1.5">
              <ClockIcon class="h-3 w-3" />
              Created {formatDate(issue.createdAt)}
            </div>
            {#if issue.updatedAt !== issue.createdAt}
              <div class="flex items-center gap-1.5">
                <ClockIcon class="h-3 w-3" />
                Updated {formatDate(issue.updatedAt)}
              </div>
            {/if}
            {#if issue.closedAt}
              <div class="flex items-center gap-1.5">
                <ClockIcon class="h-3 w-3" />
                Closed {formatDate(issue.closedAt)}
              </div>
            {/if}
          </div>
        </div>
      </div>
    {/if}
  </div>

  <ConfirmDialog
    bind:open={deleteOpen}
    title="Delete issue"
    description="Are you sure you want to delete this issue? This action cannot be undone."
    confirmLabel="Delete"
    variant="destructive"
    onConfirm={deleteIssue}
  />
</div>
