// apps/web/src/components/create-org-dialog.tsx
"use client";

import { useState } from "react";
import { useRouter } from "@/lib/navigation";
import { toast } from "sonner";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useCreateOrganization, useSetActiveOrganization } from "@/hooks/use-organization";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function CreateOrgDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const router = useRouter();
  const createOrg = useCreateOrganization();
  const setActive = useSetActiveOrganization();

  const loading = createOrg.isPending || setActive.isPending;

  const handleNameChange = (value: string) => {
    setName(value);
    setSlug(slugify(value));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !slug.trim()) return;

    try {
      const data = await createOrg.mutateAsync({
        name: name.trim(),
        slug: slug.trim(),
      });

      if (data) {
        await setActive.mutateAsync({
          organizationId: data.id,
        });
        toast.success("Team created");
        onOpenChange(false);
        setName("");
        setSlug("");
        router.push(`/org/${data.slug}`);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to create team";
      toast.error(message);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>Create team</DialogTitle>
            <DialogDescription>
              Teams are workspaces where your people track and resolve issues together.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="org-name">Name</Label>
              <Input
                id="org-name"
                placeholder="Backend"
                value={name}
                onChange={(e) => handleNameChange(e.target.value)}
                autoFocus
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="org-slug">Slug</Label>
              <Input
                id="org-slug"
                placeholder="backend"
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
              />
              <p className="text-xs text-muted-foreground">Used in URLs: /org/{slug || "..."}</p>
            </div>
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={loading || !name.trim() || !slug.trim()}>
              {loading ? "Creating..." : "Create"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// src/lib/components/create-org-dialog.svelte
<script lang="ts">
	import {
		createOrganization,
		setActiveOrganization,
		slugifyOrganizationName,
		type OrganizationSummary
	} from '$lib/organization';
	import { gotoResolvedPath } from '$lib/goto-resolved';

	import { Button } from '$lib/components/ui/button';
	import * as Dialog from '$lib/components/ui/dialog';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';

	let {
		open = $bindable(false)
	}: {
		open?: boolean;
	} = $props();

	let name = $state('');
	let slug = $state('');
	let loading = $state(false);
	let formError = $state<string | null>(null);

	function onNameInput(value: string) {
		name = value;
		slug = slugifyOrganizationName(value);
	}

	function resetForm() {
		name = '';
		slug = '';
		formError = null;
	}

	async function onSubmit(e: Event) {
		e.preventDefault();
		const trimmedName = name.trim();
		const trimmedSlug = slug.trim();
		if (!trimmedName || !trimmedSlug) return;

		loading = true;
		formError = null;

		let created: OrganizationSummary | null = null;

		try {
			created = await createOrganization({ name: trimmedName, slug: trimmedSlug });
		} catch (err) {
			formError = err instanceof Error ? err.message : 'Failed to create team';
			loading = false;
			return;
		}

		if (!created) {
			formError = 'Failed to create team';
			loading = false;
			return;
		}

		try {
			await setActiveOrganization({ organizationId: created.id });
		} catch (err) {
			formError = err instanceof Error ? err.message : 'Failed to activate team';
			loading = false;
			return;
		}

		open = false;
		resetForm();
		loading = false;
		await gotoResolvedPath(`/org/${created.slug}`);
	}
</script>

<Dialog.Root
	bind:open
	onOpenChange={(next) => {
		if (next) {
			formError = null;
		}
	}}
>
	<Dialog.Content class="sm:max-w-md">
		<form onsubmit={onSubmit}>
			<Dialog.Header>
				<Dialog.Title>Create team</Dialog.Title>
				<Dialog.Description>
					Teams are workspaces where your people track and resolve issues together.
				</Dialog.Description>
			</Dialog.Header>
			<div class="grid gap-4 py-4">
				<div class="grid gap-2">
					<Label for="org-name">Name</Label>
					<Input
						id="org-name"
						placeholder="Backend"
						value={name}
						oninput={(e) => onNameInput(e.currentTarget.value)}
					/>
				</div>
				<div class="grid gap-2">
					<Label for="org-slug">Slug</Label>
					<Input
						id="org-slug"
						placeholder="backend"
						bind:value={slug}
					/>
					<p class="text-xs text-muted-foreground">Used in URLs: /org/{slug || '…'}</p>
				</div>
				{#if formError}
					<p class="text-xs text-destructive" role="alert">{formError}</p>
				{/if}
			</div>
			<Dialog.Footer>
				<Button type="button" variant="outline" onclick={() => (open = false)}>Cancel</Button>
				<Button type="submit" disabled={loading || !name.trim() || !slug.trim()}>
					{loading ? 'Creating...' : 'Create'}
				</Button>
			</Dialog.Footer>
		</form>
	</Dialog.Content>
</Dialog.Root>
